#!/bin/sh

usage () {
  printf "Usage: build <argument>\n"
}

build_dev () {
  mkdir -p dist/
  NODE_ENV=development browserify index.js \
    --standalone=cacheElement \
    -t envify \
    > dist/cache-element.js
}

build_min () {
  mkdir -p dist/
  NODE_ENV=production browserify index.js \
    --standalone=cacheElement \
    -t envify \
    -g unassertify \
    -g uglifyify \
    -p bundle-collapser/plugin \
    | uglifyjs \
    > dist/cache-element.min.js
}

# parse CLI flags
while true; do
  case "$1" in
    -h|--help) usage && exit 1 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

case "$1" in
  d|dev) shift; build_dev "$@" ;;
  m|min) shift; build_min "$@" ;;
  *) shift; build_min "$@" ;;
esac
